name: learning_duniya
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intro_slider: ^3.0.3
  image_picker: ^0.8.4+11
  group_button: ^4.5.0
  video_player: ^2.2.3
  wakelock: ^0.6.1+2
  http: ^0.13.3
  toggle_switch: ^1.4.0
  shared_preferences: ^2.0.13
  pie_chart: ^5.3.0
  chewie: ^1.3.1
  audioplayers: ^0.20.1
  fluttertoast: ^8.0.9
  platform_device_id: ^1.0.1
  firebase_messaging: ^11.2.14
  firebase_core: ^1.15.0
  flutter_local_notifications: ^9.4.1
  url_launcher: ^6.0.18
  flutter_downloader: ^1.7.4
  flowder: ^0.2.0
  open_file: ^3.2.1
  percent_indicator: ^3.0.1






  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  favorite_button: ^0.0.4
  flutter_countdown_timer: ^4.1.0
  path_provider: ^2.0.11
  dio: ^4.0.6
  advance_pdf_viewer: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/Learning_Duniya_logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/slider.png
    - images/SignUp.png
    - images/login_top.png
    - images/SignUp_top.png
    - images/bg.png
    - images/hindi.png
    - images/english.png
    - images/computer.png
    - images/sst.png
    - images/maths.png
    - images/chemistry.png
    - images/ad.png
    - images/sci.jfif
    - images/math.jfif
    - images/mentor1.PNG
    - images/mentor2.PNG
    - images/engass.jfif
    - images/hindiass.jpg
    - images/tick.png
    - images/mentorProfile.jpeg
    - images/login.jpg
    - images/challenge.png
    - images/Learning_Duniya_logo.png
    - images/notificationno.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Candara
      fonts:
        - asset: fonts/Candara-reg.ttf
        - asset: fonts/Candara-bold.ttf
          weight: 700
        - asset: fonts/Candara-italic.ttf
          style: italic


  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
